# !-----------------------------------------------------------------------------------------------!
#                       Конфиг плагина ${project.name}
#                              Общие настройки
# !-----------------------------------------------------------------------------------------------!

# -------------------------------------------------------------------------------------------------
# Главная команда плагина, которой можно управлять им
# * Первое слово - название команды, не удалять. *
# -------------------------------------------------------------------------------------------------
Command_Aliases: [ assistant ]

# -------------------------------------------------------------------------------------------------
# Локализация плагина в папке localization "messages_*"
# -------------------------------------------------------------------------------------------------
Locale: ru

# -------------------------------------------------------------------------------------------------
# Префикс отправки сообщений от имени плагина
# -------------------------------------------------------------------------------------------------
Prefix: "&5[&f${project.name}&5]&f "

# -------------------------------------------------------------------------------------------------
# Время на выполнение каких-либо функций плагина.
# Поставь -1 для отключения.
# -------------------------------------------------------------------------------------------------
Log_Lag_Over_Milis: 100

# -------------------------------------------------------------------------------------------------
# Проверка на актуальность конфига с кодом (в коде getConfigVersion).
# -------------------------------------------------------------------------------------------------
Version: 1

# !-----------------------------------------------------------------------------------------------!
#                              Настройки плагина
# !-----------------------------------------------------------------------------------------------!